export const pageTitles = {
  '/': 'لوحة التحكم',
  '/clients': 'العملاء',
  '/contracts': 'العقود الشهرية',
  '/contracts/new': 'إضافة عقد جديد',
  '/projects': 'المشاريع',
  '/transactions': 'المعاملات المالية',
  '/invoices': 'الفواتير',
  '/accounts': 'الحسابات والمحافظ',
  '/expenses': 'المصاريف',
  '/employees': 'الموظفون',
  '/salaries': 'الرواتب',
  '/advances': 'السلف',
  '/partners': 'الشركاء والتمويل',
  '/subscriptions': 'الاشتراكات',
  '/currency-exchange': 'تحويل العملات',
  '/reports': 'التقارير',
  '/import': 'استيراد البيانات',
  '/settings/system': 'إعدادات النظام',
  '/settings/users': 'إدارة المستخدمين',
};